name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs: 
  node-version:
    required: true
    description: NodeJS version to use
    default: 20.x
  working-dir:
    description: The working directory of the application
    default: '.'
runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{inputs.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with: 
        key: node-modules-${{ hashFiles(format('{0}/{1}',inputs.working-dir,'package-lock.json') }}
        path: ${{inputs.working-dir}}/node_modules 
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != true
      run: npm ci
       #  For the custorm action we do need to provide the (shell, working directory) but in the workflow its not required.
      shell: bash
      working-directory: ${{inputs.working-dir}}
    