name: 04 - Using Actions
on: 
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@4
      - name: Printing Folders
        run : ls

