name: 14-artifacts
on: 
    workflow_dispatch
jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-artifacts/react-apps
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Download cached dependencies
              id: cache
              uses: actions/cache@v3
              with:
                key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
                path: 14-artifacts/react-app/node_modules
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != true
              run: npm ci
            - name: Unit test
              run: npm un test
            - name: Build code
              run: npm run buikd
            - name: Upload build files
              uses: actions/upload-artifact@v4
              with:
                name: app
                path: 14-artifacts/react-app/build
    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
          - name: Download build files
            uses: actions/download-artifact@v4
            with:
                name: app
                path: 14-artifacts/react-app/build
          - name: show folder structur