name: 17 - 1 - Custom Actions - Composite
on:
    workflow_dispatch:
        inputs:
             target-env:
                type: choice
                options:
                    - dev
                    - prod
run-name: 17 - 1 - Custom Actions - Composite | env - ${{inputs.tatget-env}}
env:
        # Reusing the react application rather creating new one
        working-directory: 14-artifacts/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
             run:
                # In all the run command in th Steps we need to pass the working-directory but we can set as default for run here, as declared below
                working-directory: ${{env.working-directory}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-action-cache-dep
              with:
                node-version: 20.x
                working-dir: ${{env.working-directory}}
            - name: Unit test
              run: npm run test
            - name: Build code
              run: npm run build 





