name: 18 - 3 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: dummmy-dir
  e2e-tests:
    uses: <owner>/<repo>/.github/worflows/<workflow_name.yaml>@version(version=branch_name)
    needs: deploy
    secrets:
      access-token: ${{ secrets.GH_TOKEN }}