name: 20 - Workflow Security
on: 
    pull_request: 
jobs:
    unsafe-pr:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Check PR title
              run: |
                title=${{ github.event.pull_request.title }}
                if [[ $title =~ ^feat ]]; then
                echo "PR is a feature"
                exit 0
                else
                echo "PR is not a feature"
                exit 1
                fi
    safe-pr:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Check PR title
              env : 
                TITLE: ${{ github.event.pull_request.title }}
              run: |
                if [[ $TITLE =~ ^feat ]]; then
                echo "PR is a feature"
                exit 0
                else
                echo "PR is not a feature"
                exit 1
                fi
    js-action-safe-pr:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Check PR title
              uses: ./.github/actions/securtiy-safe-input
              with: 
                pr-title: ${{ github.event.pull_request.title }}